### PR TITLE
export tweak methods

### PR DESCRIPTION
**Pull request by andkom**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feauter

* **What is the current behavior?** (You can also link to an open issue here)

https://github.com/bitjson/bitcoin-ts/issues/15

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

TODO tests

### CODE REVIEW

**Comment by bitjson** [comment]
Awesome PR, thanks for contributing! 

I'm a bit off the grid right now, so it will be a few days before I'll be able to fully review and merge. Would you be willing to add some test coverage? Please let me know if you have any trouble getting it working, I'm happy to help.

**Comment by ARitz-Cracker** [comment]
oh.... oh.........

**Comment by andkom** [comment]
> oh.... oh.........

Good job!

**Comment by andkom** [comment]
> Would you be willing to add some test coverage? 

@ARitz-Cracker did tests in his PR #17

**Pull request closed without merging**
